---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helmbot
  labels:
    app: helmbot

data:

  DEBUG: "{{ $.Values.DEBUG }}"

  ServerHostname: "{{ $.Values.ServerHostname }}"

  ConfigDir: "{{ $.Values.ConfigDir }}"

  ValuesMinioUrl: "{{ $.Values.ValuesMinioUrl }}"
  ValuesMinioUsername: "{{ $.Values.ValuesMinioUsername }}"
  ValuesMinioPassword: "{{ $.Values.ValuesMinioPassword }}"

  ConfigFilename: "{{ $.Values.ConfigFilename }}"

  TgToken: "{{ $.Values.TgToken }}"
  TgWebhookHost: "{{ $.Values.TgWebhookHost }}"
  TgWebhookUrl: "{{ $.Values.TgWebhookUrl }}"
  TgWebhookToken: "{{ $.Values.TgWebhookToken }}"
  TgChatIds: "{{ $.Values.TgChatIds }}"
  TgBossUserIds: "{{ $.Values.TgBossUserIds }}"

  LoggingHost: "{{ $.Values.LoggingHost }}"
  LoggingPort: "{{ $.Values.LoggingPort }}"
  LoggingUsername: "{{ $.Values.LoggingUsername }}"
  LoggingPassword: "{{ $.Values.LoggingPassword }}"
  LoggingTag: "{{ $.Values.LoggingTag }}"

