---

apiVersion: v1
kind: ConfigMap

metadata:
  name: helmbot
  namespace: {{ $.Release.Namespace }}
  labels:
    app: helmbot

data:

  DEBUG: "{{ $.Values.DEBUG }}"

  ServerHostname: "{{ $.Values.ServerHostname }}"

  ConfigDir: "{{ $.Values.ConfigDir }}"
  ConfigFilename: "{{ $.Values.ConfigFilename }}"
  HostConfigFilename: "{{ $.Values.HostConfigFilename }}"

  PackagesUpgradeInterval: "{{ $.Values.PackagesUpgradeInterval }}"

  ValuesMinioUrl: "{{ $.Values.ValuesMinioUrl }}"
  ValuesMinioUsername: "{{ $.Values.ValuesMinioUsername }}"
  ValuesMinioPassword: "{{ $.Values.ValuesMinioPassword }}"

  TgToken: "{{ $.Values.TgToken }}"
  TgWebhookHost: "{{ $.Values.TgWebhookHost }}"
  TgWebhookUrl: "{{ $.Values.TgWebhookUrl }}"
  TgWebhookToken: "{{ $.Values.TgWebhookToken }}"
  TgChatIds: "{{ $.Values.TgChatIds }}"
  TgBossUserIds: "{{ $.Values.TgBossUserIds }}"
  TgAdminMention: "{{ $.Values.TgAdminMention }}"

  LoggingHost: "{{ $.Values.LoggingHost }}"
  LoggingPort: "{{ $.Values.LoggingPort }}"
  LoggingUsername: "{{ $.Values.LoggingUsername }}"
  LoggingPassword: "{{ $.Values.LoggingPassword }}"
  LoggingTag: "{{ $.Values.LoggingTag }}"

