---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Namespace }}-helmbot
  labels:
    app: {{ $.Release.Namespace }}-helmbot

spec:

  replicas: 1

  selector:
    matchLabels:
      app: {{ $.Release.Namespace }}-helmbot

  template:
    metadata:
      name: {{ $.Release.Namespace }}-helmbot
      labels:
        app: {{ $.Release.Namespace }}-helmbot
      annotations:
        checksum/configmap-helmbot: {{ include ( print $.Template.BasePath "/" "configmap-helmbot.yaml" ) . | sha256sum }}

    spec:

      serviceAccountName: {{ $.Release.Namespace }}-admin-user

      imagePullSecrets:
      - name: {{ $.Release.Namespace }}-registry-helmbot-pull-secret

      containers:

        - name: {{ $.Release.Namespace }}-helmbot
          imagePullPolicy: IfNotPresent
          image: "{{ $.Values.ImageNameGithubHelmbot }}:{{ $.Values.ImageTagGithubHelmbot }}"

          {{ if $.Values.TgWebhookHost -}}
          ports:
            - containerPort: 80
          {{ end }}

          envFrom:
            - configMapRef:
                name: {{ $.Release.Namespace }}-helmbot

          volumeMounts:
            - mountPath: {{ $.Values.PackagesLocalPath }}
              name: {{ $.Release.Namespace }}-packageslocal-volume
            - mountPath: {{ $.Values.PackagesDir }}
              name: {{ $.Release.Namespace }}-packagesdir-volume
            - mountPath: /root/.kube2/
              name: {{ $.Release.Namespace }}-rootkubedir-volume

      volumes:
        - name: {{ $.Release.Namespace }}-packageslocal-volume
          persistentVolumeClaim:
            claimName: {{ $.Release.Namespace }}-packageslocal-persistentvolumeclaim
        - name: {{ $.Release.Namespace }}-packagesdir-volume
          persistentVolumeClaim:
            claimName: {{ $.Release.Namespace }}-packagesdir-persistentvolumeclaim
        - name: {{ $.Release.Namespace }}-rootkubedir-volume
          persistentVolumeClaim:
            claimName: {{ $.Release.Namespace }}-rootkubedir-persistentvolumeclaim

