{{ if and $.Values.TgWebhookHost $.Values.TgWebhookIngressRoute -}}

apiVersion: "traefik.io/v1alpha1"
kind: "IngressRoute"

metadata:
  name: "helmbot"
  namespace: "{{ $.Release.Namespace }}"

spec:
  entryPoints:
    - "websecure"

  routes:
    - kind: "Rule"
      match: "Host(`{{ $.Values.TgWebhookHost }}`)"
      services:
        - name: "helmbot"
          port: 80

{{ end }}

