---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Namespace }}-rootkubedir-persistentvolumeclaim
  labels:
    app: {{ $.Release.Namespace }}-helmbot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: {{ $.Release.Namespace }}-rootkubedir-persistentvolume
