---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Namespace }}-packageslocal-persistentvolumeclaim
  labels:
    app: {{ $.Release.Namespace }}-helmbot
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  volumeName: {{ $.Release.Namespace }}-packageslocal-persistentvolume

