---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Namespace }}-packageslocal-persistentvolume
  labels:
    type: local
    app: {{ $.Release.Namespace }}-helmbot
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: {{ $.Values.PackagesLocalPath }}
    type: File

