---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Namespace }}-packagesdir-persistentvolume
  labels:
    type: local
    app: {{ $.Release.Namespace }}-helmbot
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ $.Values.PackagesDir }}

