---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Namespace }}-registry-helmbot-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ $.Values.ImageRegistryAddress }}": {
          "username": "{{ $.Values.ImageRegistryUsername }}",
          "password": "{{ $.Values.ImageRegistryPassword }}",
          "auth": "{{ print $.Values.ImageRegistryUsername `:` $.Values.ImageRegistryPassword | b64enc }}"
        }
      }
    }

