---
{{ if $.Values.TgWebhookHost -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Namespace }}-helmbot-service
  labels:
    app: {{ $.Release.Namespace }}-helmbot
spec:
  selector:
    app: {{ $.Release.Namespace }}-helmbot
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80

{{ end }}

