---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helmbot
  labels:
    app: helmbot

spec:

  replicas: 1

  selector:
    matchLabels:
      app: helmbot

  template:
    metadata:
      name: helmbot
      labels:
        app: helmbot
      annotations:
        checksum/configmap-helmbot: {{ include ( print $.Template.BasePath "/" "configmap-helmbot.yaml" ) . | sha256sum }}

    spec:

      serviceAccountName: helmbot-admin

      volumes:
        - name: ConfigLocalDir
          hostPath:
            path: {{ $.Values.ConfigLocalDir }}
            type: DirectoryOrCreate
        - name: KubeDir
          hostPath:
            path: {{ $.Values.KubeDir }}
            type: Directory

      containers:

        - name: helmbot
          image: "{{ $.Values.ImageNameGithubHelmbot }}:{{ $.Values.ImageTagGithubHelmbot }}"
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - name: ConfigLocalDir
              mountPath: {{ $.Values.ConfigLocalDir }}
            - name: KubeDir
              mountPath: {{ $.Values.KubeDir }}

          {{ if $.Values.TgWebhookHost -}}
          ports:
            - containerPort: 80
          {{ end }}

          envFrom:
            - configMapRef:
                name: helmbot


