---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helmbot
  labels:
    app: helmbot

spec:

  replicas: 1

  selector:
    matchLabels:
      app: helmbot

  template:
    metadata:
      name: helmbot
      labels:
        app: helmbot
      annotations:
        checksum/configmap-helmbot: {{ include ( print $.Template.BasePath "/" "configmap-helmbot.yaml" ) . | sha256sum }}

    spec:

      serviceAccountName: helmbot-admin-user

      imagePullSecrets:
      - name: registry-helmbot-pull-secret

      containers:

        - name: helmbot
          imagePullPolicy: IfNotPresent
          image: "{{ $.Values.ImageNameGithubHelmbot }}:{{ $.Values.ImageTagGithubHelmbot }}"

          {{ if $.Values.TgWebhookHost -}}
          ports:
            - containerPort: 80
          {{ end }}

          envFrom:
            - configMapRef:
                name: helmbot

          volumeMounts:
            - mountPath: {{ $.Values.ConfigLocalDir }}
              name: helmbot-configlocaldir-volume
            - mountPath: /root/.kube2/
              name: helmbot-rootkubedir-volume

      volumes:
        - name: helmbot-configlocaldir-volume
          persistentVolumeClaim:
            claimName: helmbot-configlocaldir-persistentvolumeclaim
        - name: helmbot-rootkubedir-volume
          persistentVolumeClaim:
            claimName: helmbot-rootkubedir-persistentvolumeclaim


