---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helmbot
  labels:
    app: helmbot

spec:

  replicas: 1

  selector:
    matchLabels:
      app: helmbot

  template:
    metadata:
      name: helmbot
      labels:
        app: helmbot
      annotations:
        checksum/configmap-helmbot: {{ include ( print $.Template.BasePath "/" "configmap-helmbot.yaml" ) . | sha256sum }}

    spec:

      serviceAccountName: helmbot-admin

      containers:

        - name: helmbot
          imagePullPolicy: IfNotPresent
          image: "{{ $.Values.ImageNameGithubHelmbot }}:{{ $.Values.ImageTagGithubHelmbot }}"

          {{ if $.Values.TgWebhookHost -}}
          ports:
            - containerPort: 80
          {{ end }}

          envFrom:
            - configMapRef:
                name: helmbot

          volumeMounts:
            - mountPath: {{ $.Values.ConfigLocalDir }}
              hostPath:
                path: {{ $.Values.ConfigLocalDir }}
                type: DirectoryOrCreate
            - mountPath: {{ $.Values.KubeDir }}
              hostPath:
                path: {{ $.Values.KubeDir }}
                type: Directory


