---

ImageRegistryAddress: ""
ImageRegistryUsername: ""
ImageRegistryPassword: ""

ImageNameGithubHelmbot: ""


ServerHostname: ""

PackagesDir: ""

ConfigLocalPath: "/opt/helmbot/helmbot.config.yaml"
ConfigMinioPath: "helmbot.config.yaml"


TgToken: ""
TgWebhookHost: ""
TgWebhookUrl: ""
TgWebhookToken: ""
TgChatIds: ""
TgBossUserIds: ""

GetValuesUrlPrefix: ""
GetValuesUsername: ""
GetValuesPassword: ""

PutValuesUrlPrefix: ""
PutValuesUsername: ""
PutValuesPassword: ""


LoggingHost: ""
LoggingPort: ""


IngressRequestMaxBodySizeString: "1m"

IngressWhitelistSourceRange: []


