
ImageNameGithubHelmbot: "ghcr.io/shoce/helmbot/dev"
ImageTagGithubHelmbot: ""


VERBOSE: ""
DEBUG: ""

ServerHostname: ""

ConfigDir: "/opt/helmbot/"
ConfigFilename: "helmbot.config.yaml"
HostConfigFilename: "" # helmbot.config.hostname.yaml

PackagesUpgradeInterval: "333s"

ValuesS3Url: ""
ValuesS3User: ""
ValuesS3Pass: ""

TgApiUrl: ""
TgToken: ""
TgChatIds: ""
TgBossUserIds: ""
TgAdminMention: ""

TgWebhookHost: ""
TgWebhookUrl: ""
TgWebhookToken: ""

TgWebhookIngress: false
TgWebhookIngressRoute: true

LoggingHost: ""
LoggingPort: ""
LoggingUsername: ""
LoggingPassword: ""
LoggingTag: "helmbot"

LogTZ: ""


IngressRequestMaxBodySizeString: "1m"
IngressWhitelistSourceRange: []

